project/admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from project.models.accounts import UserMeta, Users
from flask_login import current_user

class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=4, max=24)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a difference one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a difference one.')


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")


class UpdateAccountForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=4, max=24)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    picture = FileField("Update Profile Picture", validators=[FileAllowed( ['jpg', 'png'] )])
    submit = SubmitField("Update")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a difference one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a difference one.')


class RequestResetForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField("Reset Password")

project/admin/routes.py
from flask import Blueprint, render_template

admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route("/admin/login")
def admin_login():
    return render_template("authen/login.html")

@admin.route("/admin/register")
def admin_register():
    return render_template("authen/register.html")

@admin.route("/admin/forgot-password")
def admin_forgot_password():
    return render_template("authen/forgot_password.html")

@admin.route("/admin/legal/terms")
def admin_legal_terms():
    return render_template("policy/terms.html")





@admin.route("/admin/profile")
def admin_profile():
    return render_template("adm/profile.html")


@admin.route("/admin/posts")
def admin_posts():
    return render_template("adm/posts.html")

@admin.route("/admin/users")
def admin_users():
    return render_template("adm/users.html")

project/admin/templates/adm/posts.html
{% extends "layout.html" %}


{% block content %}

<h1>This is posts page!!!</h1>

{% endblock content %}

project/admin/templates/adm/profile.html
{% extends "layout.html" %}


{% block content %}

<h1>This is about page!!!</h1>

{% endblock content %}

project/admin/templates/adm/users.html
{% extends "layout.html" %}


{% block content %}

<h1>This is users page!!!</h1>

{% endblock content %}

project/admin/templates/authen/forgot_password.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/admin/authen/forgot-password.css') }} " />

    <div class="page-forgot-password-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>

        <h3 class="font-size-24">Forgot Your Password ?</h3>
        <p>Input your registered email to reset your password</p>

        <form method="post" role="form" autocomplete="off">
          <div class="form-group form-material floating" data-plugin="formMaterial">
            <input type="email" class="form-control empty" id="inputEmail" name="email">
            <label class="floating-label" for="inputEmail">Your Email</label>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Reset Your Password</button>
          </div>
        </form>

        <p>No account? <a href="{{ url_for('admin.admin_register') }}">Sign Up</a></p>

        <p>Have account already? Please go to <a href="{{ url_for('admin.admin_login') }}">Sign In</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}

project/admin/templates/authen/login.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/admin/authen/login-v2.css') }} " />

    <div class="page-login-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>
        <h3 class="font-size-24">Sign In</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

        <form method="post" action="" autocomplete="off">
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="email" class="form-control empty" id="inputEmail" name="email">
                <label class="floating-label" for="inputEmail">Email</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPassword" name="password">
                <label class="floating-label" for="inputPassword">Password</label>
            </div>
            <div class="form-group clearfix">
                <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
                    <input type="checkbox" id="remember" name="checkbox" />
                    <label for="inputCheckbox">Remember me</label>
                </div>
                <a class="float-right" href="{{ url_for('admin.admin_forgot_password') }}">Forgot password?</a>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
        </form>

        <p>No account? <a href="{{ url_for('admin.admin_register') }}">Sign Up</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}

project/admin/templates/authen/register.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css"
          href=" {{ url_for('static', filename='css/admin/authen/register-v2.css') }} "/>

    <div class="page-register-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>
        <h3 class="font-size-24">Sign Up</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

        <form method="post" role="form" autocomplete="off">
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="text" class="form-control empty" id="inputName" name="name">
                <label class="floating-label" for="inputName">Name</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="email" class="form-control empty" id="inputEmail" name="email">
                <label class="floating-label" for="inputEmail">Email</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPassword" name="password">
                <label class="floating-label" for="inputPassword">Password</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPasswordCheck" name="passwordCheck">
                <label class="floating-label" for="inputPasswordCheck">Retype Password</label>
            </div>
            <div class="form-group clearfix">
                <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
                    <input type="checkbox" id="inputCheckbox" name="term">
                    <label for="inputCheckbox"></label>
                </div>
                <p class="ml-35">By clicking Sign Up, you agree to our <a href="{{ url_for('admin.admin_legal_terms') }}">Terms</a>.</p>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </form>

        <p>Have account already? Please go to <a href="{{ url_for('admin.admin_login') }}">Sign In</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}

project/admin/templates/layout.html
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="bootstrap material admin template">
    <meta name="author" content="">

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/plugins/bootstrap/bootstrap.min.css') }} " />
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/plugins/bootstrap/bootstrap-extend.min.css') }} " />
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/admin/site.css') }} " />


        <!-- Plugins -->
    <link rel="stylesheet" href="../../global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="../../global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="../../global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="../../global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="../../global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="../../global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="../../global/vendor/waves/waves.css">
    <link rel="stylesheet" href="../../global/vendor/chartist/chartist.css">
    <link rel="stylesheet" href="../../global/vendor/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="../../global/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css">
    <link rel="stylesheet" href="../assets/examples/css/dashboard/v1.css">



    <!-- Fonts -->
    <link rel="stylesheet" href=" {{ url_for('static', filename='fonts/material-design/material-design.min.css') }} " />
    <link rel="stylesheet" href=" {{ url_for('static', filename='fonts/brand-icons/brand-icons.min.css') }} " />
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic' />


    <!--[if lt IE 9]>
    <script src="../../global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->

    <!--[if lt IE 10]>
    <script src="../../global/vendor/media-match/media.match.min.js"></script>
    <script src="../../global/vendor/respond/respond.min.js"></script>
    <![endif]-->

    <!-- Scripts -->
    <script src="../../global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>


    <!-- If we pass through title, It will add to main title -->
    {% if title %}
    <title>Flask Blog -- {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">

            <!-- This is message popup when any event occurs -->
            <!--with_categories=true: mean we can get the class of alert we passing through -->
            <!--messages: have 2 component (category - alert class, message) -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{message}}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <!-- This is our layout content for all page, every page will extends and override this content -->
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <div class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </div>
            </div>
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>


    <!-- Core  -->
    <script src="../../global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
    <script src="../../global/vendor/jquery/jquery.js"></script>
    <script src="../../global/vendor/popper-js/umd/popper.min.js"></script>
    <script src="../../global/vendor/bootstrap/bootstrap.js"></script>
    <script src="../../global/vendor/animsition/animsition.js"></script>
    <script src="../../global/vendor/mousewheel/jquery.mousewheel.js"></script>
    <script src="../../global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
    <script src="../../global/vendor/asscrollable/jquery-asScrollable.js"></script>
    <script src="../../global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
    <script src="../../global/vendor/waves/waves.js"></script>

    <!-- Plugins -->
    <script src="../../global/vendor/switchery/switchery.js"></script>
    <script src="../../global/vendor/intro-js/intro.js"></script>
    <script src="../../global/vendor/screenfull/screenfull.js"></script>
    <script src="../../global/vendor/slidepanel/jquery-slidePanel.js"></script>
        <script src="../../global/vendor/chartist/chartist.min.js"></script>
        <script src="../../global/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.js"></script>
        <script src="../../global/vendor/jvectormap/jquery-jvectormap.min.js"></script>
        <script src="../../global/vendor/jvectormap/maps/jquery-jvectormap-world-mill-en.js"></script>
        <script src="../../global/vendor/matchheight/jquery.matchHeight-min.js"></script>
        <script src="../../global/vendor/peity/jquery.peity.min.js"></script>

    <!-- Scripts -->
    <script src="../../global/js/Component.js"></script>
    <script src="../../global/js/Plugin.js"></script>
    <script src="../../global/js/Base.js"></script>
    <script src="../../global/js/Config.js"></script>

    <script src="../assets/js/Section/Menubar.js"></script>
    <script src="../assets/js/Section/Sidebar.js"></script>
    <script src="../assets/js/Section/PageAside.js"></script>
    <script src="../assets/js/Plugin/menu.js"></script>

    <!-- Config -->
    <script src="../../global/js/config/colors.js"></script>
    <script src="../assets/js/config/tour.js"></script>
    <script>Config.set('assets', '../assets');</script>

    <!-- Page -->
    <script src="../assets/js/Site.js"></script>
    <script src="../../global/js/Plugin/asscrollable.js"></script>
    <script src="../../global/js/Plugin/slidepanel.js"></script>
    <script src="../../global/js/Plugin/switchery.js"></script>
        <script src="../../global/js/Plugin/matchheight.js"></script>
        <script src="../../global/js/Plugin/jvectormap.js"></script>
        <script src="../../global/js/Plugin/peity.js"></script>

        <script src="../assets/examples/js/dashboard/v1.js"></script>

</body>
</html>

project/admin/templates/policy/cookie_policy.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css"
          href=" {{ url_for('static', filename='css/admin/authen/register-v2.css') }} "/>

    <div class="page-register-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>
        <h3 class="font-size-24">Sign Up</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

        <form method="post" role="form" autocomplete="off">
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="text" class="form-control empty" id="inputName" name="name">
                <label class="floating-label" for="inputName">Name</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="email" class="form-control empty" id="inputEmail" name="email">
                <label class="floating-label" for="inputEmail">Email</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPassword" name="password">
                <label class="floating-label" for="inputPassword">Password</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPasswordCheck" name="passwordCheck">
                <label class="floating-label" for="inputPasswordCheck">Retype Password</label>
            </div>
            <div class="form-group clearfix">
                <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
                    <input type="checkbox" id="inputCheckbox" name="term">
                    <label for="inputCheckbox"></label>
                </div>
                <p class="ml-35">By clicking Sign Up, you agree to our <a href="{{ url_for('admin.admin_terms') }}">Terms</a>.</p>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </form>

        <p>Have account already? Please go to <a href="{{ url_for('admin.admin_login') }}">Sign In</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}

project/admin/templates/policy/data_policy.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/admin/authen/login-v2.css') }} " />

    <div class="page-login-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>
        <h3 class="font-size-24">Sign In</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

        <form method="post" action="" autocomplete="off">
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="email" class="form-control empty" id="inputEmail" name="email">
                <label class="floating-label" for="inputEmail">Email</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
                <input type="password" class="form-control empty" id="inputPassword" name="password">
                <label class="floating-label" for="inputPassword">Password</label>
            </div>
            <div class="form-group clearfix">
                <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
                    <input type="checkbox" id="remember" name="checkbox" />
                    <label for="inputCheckbox">Remember me</label>
                </div>
                <a class="float-right" href="{{ url_for('admin.admin_forgot_password') }}">Forgot password?</a>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
        </form>

        <p>No account? <a href="{{ url_for('admin.admin_register') }}">Sign Up</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}

project/admin/templates/policy/terms.html
{% extends "layout_authen.html" %}

{% block content %}

    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/admin/authen/forgot-password.css') }} " />

    <div class="page-forgot-password-main">
        <div class="brand hidden-md-up">
            <img class="brand-img" src=" {{ url_for('static', filename='images/admin/logo-colored-2x.png') }} "/>
            <h3 class="brand-text font-size-40">Remark</h3>
        </div>

        <h3 class="font-size-24">Forgot Your Password ?</h3>
        <p>Input your registered email to reset your password</p>

        <form method="post" role="form" autocomplete="off">
          <div class="form-group form-material floating" data-plugin="formMaterial">
            <input type="email" class="form-control empty" id="inputEmail" name="email">
            <label class="floating-label" for="inputEmail">Your Email</label>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Reset Your Password</button>
          </div>
        </form>

        <p>No account? <a href="{{ url_for('admin.admin_register') }}">Sign Up</a></p>

        <p>Have account already? Please go to <a href="{{ url_for('admin.admin_login') }}">Sign In</a></p>

        <footer class="page-copyright">
            <p>WEBSITE BY sunsight-bk Team © 2018</p>
            <div class="social">
                <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
                    <i class="icon bd-google-plus" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
    </div>

{% endblock content %}